// ===========================================================================
// logo-content.js — YOUR BRAND BANK + logo.dev token.
// Only the HOST loads this file, so the answers stay off players' devices.
// Nothing copyrighted is stored here — just company domains. The actual logo
// images are fetched live from logo.dev at runtime.
//
// >>> PASTE YOUR logo.dev PUBLISHABLE TOKEN BELOW (get one free at logo.dev) <<<
// ===========================================================================
export const LOGODEV_TOKEN = "pk_YCYSOoGWSHCIMcDHbn9IFA";

// Build the logo image URL for a domain (edit here if you ever switch providers).
// LOGO_REV: bump this number any time you want every client to re-pull fresh
// logos from logo.dev (it changes the URL, so browsers discard cached copies).
export const LOGO_REV = 2;
export function logoUrl(domain) {
  return `https://img.logo.dev/${domain}?token=${LOGODEV_TOKEN}&size=512&format=png&retina=true&rev=${LOGO_REV}`;
}

export const CATEGORIES = [
  "Technology", "Food & Beverage", "Fashion", "Automotive", "Airlines",
  "Sports", "Banking & Finance", "E-commerce", "Entertainment", "Retail",
  "Social Media", "Luxury Brands", "Travel & Hospitality", "Consumer Goods", "Healthcare",
];

// Each entry: { domain, answer, accept:[lowercase variations], category }
// The matcher strips spaces/punctuation and lowercases, so "coca cola",
// "Coca-Cola" and "cocacola" all match if any normalized form is in accept.
export const LOGOS = [
  { domain: "apple.com", answer: "Apple", accept: [], category: "Technology" },
  { domain: "microsoft.com", answer: "Microsoft", accept: ["ms"], category: "Technology" },
  { domain: "google.com", answer: "Google", accept: [], category: "Technology" },
  { domain: "intel.com", answer: "Intel", accept: [], category: "Technology" },
  { domain: "nvidia.com", answer: "Nvidia", accept: [], category: "Technology" },
  { domain: "samsung.com", answer: "Samsung", accept: [], category: "Technology" },
  { domain: "adobe.com", answer: "Adobe", accept: [], category: "Technology" },
  { domain: "ibm.com", answer: "IBM", accept: [], category: "Technology" },
  { domain: "sony.com", answer: "Sony", accept: [], category: "Technology" },
  { domain: "lg.com", answer: "LG", accept: [], category: "Technology" },
  { domain: "hp.com", answer: "HP", accept: ["hewlett packard"], category: "Technology" },
  { domain: "dell.com", answer: "Dell", accept: [], category: "Technology" },
  { domain: "lenovo.com", answer: "Lenovo", accept: [], category: "Technology" },
  { domain: "asus.com", answer: "Asus", accept: [], category: "Technology" },
  { domain: "acer.com", answer: "Acer", accept: [], category: "Technology" },
  { domain: "oracle.com", answer: "Oracle", accept: [], category: "Technology" },
  { domain: "sap.com", answer: "SAP", accept: [], category: "Technology" },
  { domain: "salesforce.com", answer: "Salesforce", accept: [], category: "Technology" },
  { domain: "cisco.com", answer: "Cisco", accept: [], category: "Technology" },
  { domain: "amd.com", answer: "AMD", accept: [], category: "Technology" },
  { domain: "qualcomm.com", answer: "Qualcomm", accept: [], category: "Technology" },
  { domain: "huawei.com", answer: "Huawei", accept: [], category: "Technology" },
  { domain: "xiaomi.com", answer: "Xiaomi", accept: [], category: "Technology" },
  { domain: "canon.com", answer: "Canon", accept: [], category: "Technology" },
  { domain: "panasonic.com", answer: "Panasonic", accept: [], category: "Technology" },
  { domain: "philips.com", answer: "Philips", accept: [], category: "Technology" },
  { domain: "siemens.com", answer: "Siemens", accept: [], category: "Technology" },
  { domain: "logitech.com", answer: "Logitech", accept: [], category: "Technology" },
  { domain: "github.com", answer: "GitHub", accept: [], category: "Technology" },
  { domain: "dropbox.com", answer: "Dropbox", accept: [], category: "Technology" },
  { domain: "slack.com", answer: "Slack", accept: [], category: "Technology" },
  { domain: "zoom.us", answer: "Zoom", accept: [], category: "Technology" },
  { domain: "nokia.com", answer: "Nokia", accept: [], category: "Technology" },
  { domain: "motorola.com", answer: "Motorola", accept: [], category: "Technology" },
  { domain: "mcdonalds.com", answer: "McDonald's", accept: ["mcdonalds"], category: "Food & Beverage" },
  { domain: "coca-cola.com", answer: "Coca-Cola", accept: ["coke", "cocacola"], category: "Food & Beverage" },
  { domain: "pepsi.com", answer: "Pepsi", accept: [], category: "Food & Beverage" },
  { domain: "starbucks.com", answer: "Starbucks", accept: [], category: "Food & Beverage" },
  { domain: "kfc.com", answer: "KFC", accept: ["kentucky fried chicken"], category: "Food & Beverage" },
  { domain: "burgerking.com", answer: "Burger King", accept: ["bk"], category: "Food & Beverage" },
  { domain: "nestle.com", answer: "Nestlé", accept: ["nestle"], category: "Food & Beverage" },
  { domain: "dominos.com", answer: "Domino's", accept: ["dominos"], category: "Food & Beverage" },
  { domain: "subway.com", answer: "Subway", accept: [], category: "Food & Beverage" },
  { domain: "pizzahut.com", answer: "Pizza Hut", accept: [], category: "Food & Beverage" },
  { domain: "wendys.com", answer: "Wendy's", accept: ["wendys"], category: "Food & Beverage" },
  { domain: "tacobell.com", answer: "Taco Bell", accept: [], category: "Food & Beverage" },
  { domain: "dunkindonuts.com", answer: "Dunkin'", accept: ["dunkin", "dunkin donuts"], category: "Food & Beverage" },
  { domain: "chipotle.com", answer: "Chipotle", accept: [], category: "Food & Beverage" },
  { domain: "heinz.com", answer: "Heinz", accept: [], category: "Food & Beverage" },
  { domain: "kelloggs.com", answer: "Kellogg's", accept: ["kelloggs"], category: "Food & Beverage" },
  { domain: "oreo.com", answer: "Oreo", accept: [], category: "Food & Beverage" },
  { domain: "nutella.com", answer: "Nutella", accept: [], category: "Food & Beverage" },
  { domain: "redbull.com", answer: "Red Bull", accept: [], category: "Food & Beverage" },
  { domain: "monsterenergy.com", answer: "Monster", accept: ["monster energy"], category: "Food & Beverage" },
  { domain: "gatorade.com", answer: "Gatorade", accept: [], category: "Food & Beverage" },
  { domain: "fanta.com", answer: "Fanta", accept: [], category: "Food & Beverage" },
  { domain: "lays.com", answer: "Lay's", accept: ["lays"], category: "Food & Beverage" },
  { domain: "doritos.com", answer: "Doritos", accept: [], category: "Food & Beverage" },
  { domain: "pringles.com", answer: "Pringles", accept: [], category: "Food & Beverage" },
  { domain: "hershey.com", answer: "Hershey's", accept: ["hersheys", "hershey"], category: "Food & Beverage" },
  { domain: "snickers.com", answer: "Snickers", accept: [], category: "Food & Beverage" },
  { domain: "cadbury.co.uk", answer: "Cadbury", accept: [], category: "Food & Beverage" },
  { domain: "benjerry.com", answer: "Ben & Jerry's", accept: ["ben and jerrys", "ben jerrys"], category: "Food & Beverage" },
  { domain: "lindt.com", answer: "Lindt", accept: [], category: "Food & Beverage" },
  { domain: "mms.com", answer: "M&M's", accept: ["mms", "m and ms"], category: "Food & Beverage" },
  { domain: "nike.com", answer: "Nike", accept: [], category: "Fashion" },
  { domain: "adidas.com", answer: "Adidas", accept: [], category: "Fashion" },
  { domain: "puma.com", answer: "Puma", accept: [], category: "Fashion" },
  { domain: "zara.com", answer: "Zara", accept: [], category: "Fashion" },
  { domain: "hm.com", answer: "H&M", accept: ["hm", "h and m"], category: "Fashion" },
  { domain: "levi.com", answer: "Levi's", accept: ["levis"], category: "Fashion" },
  { domain: "underarmour.com", answer: "Under Armour", accept: ["under armor", "ua"], category: "Fashion" },
  { domain: "ralphlauren.com", answer: "Ralph Lauren", accept: ["polo"], category: "Fashion" },
  { domain: "gap.com", answer: "Gap", accept: [], category: "Fashion" },
  { domain: "uniqlo.com", answer: "Uniqlo", accept: [], category: "Fashion" },
  { domain: "vans.com", answer: "Vans", accept: [], category: "Fashion" },
  { domain: "converse.com", answer: "Converse", accept: [], category: "Fashion" },
  { domain: "newbalance.com", answer: "New Balance", accept: [], category: "Fashion" },
  { domain: "calvinklein.com", answer: "Calvin Klein", accept: ["ck"], category: "Fashion" },
  { domain: "tommy.com", answer: "Tommy Hilfiger", accept: ["tommy hilfiger"], category: "Fashion" },
  { domain: "lacoste.com", answer: "Lacoste", accept: [], category: "Fashion" },
  { domain: "thenorthface.com", answer: "The North Face", accept: ["north face"], category: "Fashion" },
  { domain: "champion.com", answer: "Champion", accept: [], category: "Fashion" },
  { domain: "guess.com", answer: "Guess", accept: [], category: "Fashion" },
  { domain: "victoriassecret.com", answer: "Victoria's Secret", accept: ["victorias secret"], category: "Fashion" },
  { domain: "crocs.com", answer: "Crocs", accept: [], category: "Fashion" },
  { domain: "timberland.com", answer: "Timberland", accept: [], category: "Fashion" },
  { domain: "drmartens.com", answer: "Dr. Martens", accept: ["dr martens", "doc martens"], category: "Fashion" },
  { domain: "fila.com", answer: "Fila", accept: [], category: "Fashion" },
  { domain: "skechers.com", answer: "Skechers", accept: [], category: "Fashion" },
  { domain: "forever21.com", answer: "Forever 21", accept: ["forever21"], category: "Fashion" },
  { domain: "toyota.com", answer: "Toyota", accept: [], category: "Automotive" },
  { domain: "bmw.com", answer: "BMW", accept: [], category: "Automotive" },
  { domain: "mercedes-benz.com", answer: "Mercedes-Benz", accept: ["mercedes", "benz"], category: "Automotive" },
  { domain: "honda.com", answer: "Honda", accept: [], category: "Automotive" },
  { domain: "ford.com", answer: "Ford", accept: [], category: "Automotive" },
  { domain: "volkswagen.com", answer: "Volkswagen", accept: ["vw"], category: "Automotive" },
  { domain: "tesla.com", answer: "Tesla", accept: [], category: "Automotive" },
  { domain: "ferrari.com", answer: "Ferrari", accept: [], category: "Automotive" },
  { domain: "audi.com", answer: "Audi", accept: [], category: "Automotive" },
  { domain: "nissanusa.com", answer: "Nissan", accept: [], category: "Automotive" },
  { domain: "chevrolet.com", answer: "Chevrolet", accept: ["chevy"], category: "Automotive" },
  { domain: "hyundai.com", answer: "Hyundai", accept: [], category: "Automotive" },
  { domain: "kia.com", answer: "Kia", accept: [], category: "Automotive" },
  { domain: "mazda.com", answer: "Mazda", accept: [], category: "Automotive" },
  { domain: "subaru.com", answer: "Subaru", accept: [], category: "Automotive" },
  { domain: "lexus.com", answer: "Lexus", accept: [], category: "Automotive" },
  { domain: "porsche.com", answer: "Porsche", accept: [], category: "Automotive" },
  { domain: "lamborghini.com", answer: "Lamborghini", accept: ["lambo"], category: "Automotive" },
  { domain: "jeep.com", answer: "Jeep", accept: [], category: "Automotive" },
  { domain: "volvocars.com", answer: "Volvo", accept: [], category: "Automotive" },
  { domain: "jaguar.com", answer: "Jaguar", accept: [], category: "Automotive" },
  { domain: "landrover.com", answer: "Land Rover", accept: [], category: "Automotive" },
  { domain: "bugatti.com", answer: "Bugatti", accept: [], category: "Automotive" },
  { domain: "bentleymotors.com", answer: "Bentley", accept: [], category: "Automotive" },
  { domain: "rolls-roycemotorcars.com", answer: "Rolls-Royce", accept: ["rolls royce"], category: "Automotive" },
  { domain: "mitsubishicars.com", answer: "Mitsubishi", accept: [], category: "Automotive" },
  { domain: "peugeot.com", answer: "Peugeot", accept: [], category: "Automotive" },
  { domain: "renault.fr", answer: "Renault", accept: [], category: "Automotive" },
  { domain: "fiat.com", answer: "Fiat", accept: [], category: "Automotive" },
  { domain: "dodge.com", answer: "Dodge", accept: [], category: "Automotive" },
  { domain: "cadillac.com", answer: "Cadillac", accept: [], category: "Automotive" },
  { domain: "maserati.com", answer: "Maserati", accept: [], category: "Automotive" },
  { domain: "emirates.com", answer: "Emirates", accept: [], category: "Airlines" },
  { domain: "delta.com", answer: "Delta", accept: ["delta air lines"], category: "Airlines" },
  { domain: "united.com", answer: "United Airlines", accept: ["united"], category: "Airlines" },
  { domain: "aa.com", answer: "American Airlines", accept: ["american airlines", "aa"], category: "Airlines" },
  { domain: "lufthansa.com", answer: "Lufthansa", accept: [], category: "Airlines" },
  { domain: "qatarairways.com", answer: "Qatar Airways", accept: ["qatar"], category: "Airlines" },
  { domain: "singaporeair.com", answer: "Singapore Airlines", accept: ["singapore air"], category: "Airlines" },
  { domain: "southwest.com", answer: "Southwest", accept: ["southwest airlines"], category: "Airlines" },
  { domain: "britishairways.com", answer: "British Airways", accept: ["ba"], category: "Airlines" },
  { domain: "airfrance.com", answer: "Air France", accept: [], category: "Airlines" },
  { domain: "klm.com", answer: "KLM", accept: [], category: "Airlines" },
  { domain: "ryanair.com", answer: "Ryanair", accept: [], category: "Airlines" },
  { domain: "easyjet.com", answer: "easyJet", accept: ["easyjet"], category: "Airlines" },
  { domain: "jetblue.com", answer: "JetBlue", accept: [], category: "Airlines" },
  { domain: "alaskaair.com", answer: "Alaska Airlines", accept: ["alaska air"], category: "Airlines" },
  { domain: "turkishairlines.com", answer: "Turkish Airlines", accept: [], category: "Airlines" },
  { domain: "cathaypacific.com", answer: "Cathay Pacific", accept: ["cathay"], category: "Airlines" },
  { domain: "etihad.com", answer: "Etihad", accept: [], category: "Airlines" },
  { domain: "ana.co.jp", answer: "ANA", accept: ["all nippon"], category: "Airlines" },
  { domain: "qantas.com", answer: "Qantas", accept: [], category: "Airlines" },
  { domain: "aircanada.com", answer: "Air Canada", accept: [], category: "Airlines" },
  { domain: "spirit.com", answer: "Spirit Airlines", accept: ["spirit"], category: "Airlines" },
  { domain: "flyfrontier.com", answer: "Frontier", accept: ["frontier airlines"], category: "Airlines" },
  { domain: "nba.com", answer: "NBA", accept: [], category: "Sports" },
  { domain: "nfl.com", answer: "NFL", accept: [], category: "Sports" },
  { domain: "mlb.com", answer: "MLB", accept: ["major league baseball"], category: "Sports" },
  { domain: "nhl.com", answer: "NHL", accept: [], category: "Sports" },
  { domain: "espn.com", answer: "ESPN", accept: [], category: "Sports" },
  { domain: "fifa.com", answer: "FIFA", accept: [], category: "Sports" },
  { domain: "uefa.com", answer: "UEFA", accept: [], category: "Sports" },
  { domain: "olympics.com", answer: "Olympics", accept: ["olympic", "ioc"], category: "Sports" },
  { domain: "ufc.com", answer: "UFC", accept: [], category: "Sports" },
  { domain: "nascar.com", answer: "NASCAR", accept: [], category: "Sports" },
  { domain: "pgatour.com", answer: "PGA Tour", accept: ["pga"], category: "Sports" },
  { domain: "premierleague.com", answer: "Premier League", accept: ["epl"], category: "Sports" },
  { domain: "formula1.com", answer: "Formula 1", accept: ["f1", "formula one"], category: "Sports" },
  { domain: "wilson.com", answer: "Wilson", accept: [], category: "Sports" },
  { domain: "reebok.com", answer: "Reebok", accept: [], category: "Sports" },
  { domain: "spalding.com", answer: "Spalding", accept: [], category: "Sports" },
  { domain: "wimbledon.com", answer: "Wimbledon", accept: [], category: "Sports" },
  { domain: "worldrugby.org", answer: "World Rugby", accept: [], category: "Sports" },
  { domain: "visa.com", answer: "Visa", accept: [], category: "Banking & Finance" },
  { domain: "mastercard.com", answer: "Mastercard", accept: ["master card"], category: "Banking & Finance" },
  { domain: "paypal.com", answer: "PayPal", accept: [], category: "Banking & Finance" },
  { domain: "americanexpress.com", answer: "American Express", accept: ["amex"], category: "Banking & Finance" },
  { domain: "chase.com", answer: "Chase", accept: ["jpmorgan chase", "jp morgan"], category: "Banking & Finance" },
  { domain: "goldmansachs.com", answer: "Goldman Sachs", accept: ["goldman"], category: "Banking & Finance" },
  { domain: "hsbc.com", answer: "HSBC", accept: [], category: "Banking & Finance" },
  { domain: "wellsfargo.com", answer: "Wells Fargo", accept: [], category: "Banking & Finance" },
  { domain: "bankofamerica.com", answer: "Bank of America", accept: ["bofa"], category: "Banking & Finance" },
  { domain: "citi.com", answer: "Citi", accept: ["citibank"], category: "Banking & Finance" },
  { domain: "morganstanley.com", answer: "Morgan Stanley", accept: [], category: "Banking & Finance" },
  { domain: "barclays.com", answer: "Barclays", accept: [], category: "Banking & Finance" },
  { domain: "db.com", answer: "Deutsche Bank", accept: [], category: "Banking & Finance" },
  { domain: "santander.com", answer: "Santander", accept: [], category: "Banking & Finance" },
  { domain: "capitalone.com", answer: "Capital One", accept: [], category: "Banking & Finance" },
  { domain: "discover.com", answer: "Discover", accept: [], category: "Banking & Finance" },
  { domain: "stripe.com", answer: "Stripe", accept: [], category: "Banking & Finance" },
  { domain: "venmo.com", answer: "Venmo", accept: [], category: "Banking & Finance" },
  { domain: "robinhood.com", answer: "Robinhood", accept: [], category: "Banking & Finance" },
  { domain: "coinbase.com", answer: "Coinbase", accept: [], category: "Banking & Finance" },
  { domain: "fidelity.com", answer: "Fidelity", accept: [], category: "Banking & Finance" },
  { domain: "schwab.com", answer: "Charles Schwab", accept: ["schwab"], category: "Banking & Finance" },
  { domain: "vanguard.com", answer: "Vanguard", accept: [], category: "Banking & Finance" },
  { domain: "blackrock.com", answer: "BlackRock", accept: [], category: "Banking & Finance" },
  { domain: "ally.com", answer: "Ally", accept: [], category: "Banking & Finance" },
  { domain: "amazon.com", answer: "Amazon", accept: [], category: "E-commerce" },
  { domain: "ebay.com", answer: "eBay", accept: [], category: "E-commerce" },
  { domain: "alibaba.com", answer: "Alibaba", accept: [], category: "E-commerce" },
  { domain: "shopify.com", answer: "Shopify", accept: [], category: "E-commerce" },
  { domain: "etsy.com", answer: "Etsy", accept: [], category: "E-commerce" },
  { domain: "aliexpress.com", answer: "AliExpress", accept: [], category: "E-commerce" },
  { domain: "wayfair.com", answer: "Wayfair", accept: [], category: "E-commerce" },
  { domain: "mercadolibre.com", answer: "Mercado Libre", accept: [], category: "E-commerce" },
  { domain: "rakuten.com", answer: "Rakuten", accept: [], category: "E-commerce" },
  { domain: "flipkart.com", answer: "Flipkart", accept: [], category: "E-commerce" },
  { domain: "temu.com", answer: "Temu", accept: [], category: "E-commerce" },
  { domain: "shein.com", answer: "Shein", accept: [], category: "E-commerce" },
  { domain: "asos.com", answer: "ASOS", accept: [], category: "E-commerce" },
  { domain: "newegg.com", answer: "Newegg", accept: [], category: "E-commerce" },
  { domain: "wish.com", answer: "Wish", accept: [], category: "E-commerce" },
  { domain: "zalando.com", answer: "Zalando", accept: [], category: "E-commerce" },
  { domain: "chewy.com", answer: "Chewy", accept: [], category: "E-commerce" },
  { domain: "overstock.com", answer: "Overstock", accept: [], category: "E-commerce" },
  { domain: "groupon.com", answer: "Groupon", accept: [], category: "E-commerce" },
  { domain: "instacart.com", answer: "Instacart", accept: [], category: "E-commerce" },
  { domain: "netflix.com", answer: "Netflix", accept: [], category: "Entertainment" },
  { domain: "disney.com", answer: "Disney", accept: ["walt disney"], category: "Entertainment" },
  { domain: "spotify.com", answer: "Spotify", accept: [], category: "Entertainment" },
  { domain: "youtube.com", answer: "YouTube", accept: [], category: "Entertainment" },
  { domain: "hbo.com", answer: "HBO", accept: ["hbo max", "max"], category: "Entertainment" },
  { domain: "marvel.com", answer: "Marvel", accept: [], category: "Entertainment" },
  { domain: "nintendo.com", answer: "Nintendo", accept: [], category: "Entertainment" },
  { domain: "playstation.com", answer: "PlayStation", accept: ["ps"], category: "Entertainment" },
  { domain: "xbox.com", answer: "Xbox", accept: [], category: "Entertainment" },
  { domain: "hulu.com", answer: "Hulu", accept: [], category: "Entertainment" },
  { domain: "primevideo.com", answer: "Prime Video", accept: ["amazon prime video"], category: "Entertainment" },
  { domain: "warnerbros.com", answer: "Warner Bros", accept: ["warner brothers"], category: "Entertainment" },
  { domain: "universalpictures.com", answer: "Universal", accept: ["universal pictures"], category: "Entertainment" },
  { domain: "paramount.com", answer: "Paramount", accept: [], category: "Entertainment" },
  { domain: "pixar.com", answer: "Pixar", accept: [], category: "Entertainment" },
  { domain: "dreamworks.com", answer: "DreamWorks", accept: [], category: "Entertainment" },
  { domain: "twitch.tv", answer: "Twitch", accept: [], category: "Entertainment" },
  { domain: "imdb.com", answer: "IMDb", accept: [], category: "Entertainment" },
  { domain: "steampowered.com", answer: "Steam", accept: [], category: "Entertainment" },
  { domain: "ea.com", answer: "EA", accept: ["electronic arts"], category: "Entertainment" },
  { domain: "ubisoft.com", answer: "Ubisoft", accept: [], category: "Entertainment" },
  { domain: "activision.com", answer: "Activision", accept: [], category: "Entertainment" },
  { domain: "sega.com", answer: "Sega", accept: [], category: "Entertainment" },
  { domain: "epicgames.com", answer: "Epic Games", accept: ["epic"], category: "Entertainment" },
  { domain: "dolby.com", answer: "Dolby", accept: [], category: "Entertainment" },
  { domain: "imax.com", answer: "IMAX", accept: [], category: "Entertainment" },
  { domain: "soundcloud.com", answer: "SoundCloud", accept: [], category: "Entertainment" },
  { domain: "mtv.com", answer: "MTV", accept: [], category: "Entertainment" },
  { domain: "cnn.com", answer: "CNN", accept: [], category: "Entertainment" },
  { domain: "bbc.com", answer: "BBC", accept: [], category: "Entertainment" },
  { domain: "walmart.com", answer: "Walmart", accept: [], category: "Retail" },
  { domain: "target.com", answer: "Target", accept: [], category: "Retail" },
  { domain: "costco.com", answer: "Costco", accept: [], category: "Retail" },
  { domain: "ikea.com", answer: "IKEA", accept: [], category: "Retail" },
  { domain: "bestbuy.com", answer: "Best Buy", accept: [], category: "Retail" },
  { domain: "homedepot.com", answer: "Home Depot", accept: [], category: "Retail" },
  { domain: "lowes.com", answer: "Lowe's", accept: ["lowes"], category: "Retail" },
  { domain: "aldi.com", answer: "Aldi", accept: [], category: "Retail" },
  { domain: "kroger.com", answer: "Kroger", accept: [], category: "Retail" },
  { domain: "walgreens.com", answer: "Walgreens", accept: [], category: "Retail" },
  { domain: "7-eleven.com", answer: "7-Eleven", accept: ["7 eleven", "seven eleven"], category: "Retail" },
  { domain: "macys.com", answer: "Macy's", accept: ["macys"], category: "Retail" },
  { domain: "nordstrom.com", answer: "Nordstrom", accept: [], category: "Retail" },
  { domain: "sephora.com", answer: "Sephora", accept: [], category: "Retail" },
  { domain: "lidl.com", answer: "Lidl", accept: [], category: "Retail" },
  { domain: "tesco.com", answer: "Tesco", accept: [], category: "Retail" },
  { domain: "carrefour.com", answer: "Carrefour", accept: [], category: "Retail" },
  { domain: "dollargeneral.com", answer: "Dollar General", accept: [], category: "Retail" },
  { domain: "wholefoodsmarket.com", answer: "Whole Foods", accept: [], category: "Retail" },
  { domain: "traderjoes.com", answer: "Trader Joe's", accept: ["trader joes"], category: "Retail" },
  { domain: "cvs.com", answer: "CVS", accept: ["cvs pharmacy"], category: "Retail" },
  { domain: "gamestop.com", answer: "GameStop", accept: [], category: "Retail" },
  { domain: "facebook.com", answer: "Facebook", accept: ["fb", "meta"], category: "Social Media" },
  { domain: "instagram.com", answer: "Instagram", accept: ["insta", "ig"], category: "Social Media" },
  { domain: "x.com", answer: "X (Twitter)", accept: ["x", "twitter"], category: "Social Media" },
  { domain: "linkedin.com", answer: "LinkedIn", accept: [], category: "Social Media" },
  { domain: "tiktok.com", answer: "TikTok", accept: ["tik tok"], category: "Social Media" },
  { domain: "snapchat.com", answer: "Snapchat", accept: ["snap"], category: "Social Media" },
  { domain: "reddit.com", answer: "Reddit", accept: [], category: "Social Media" },
  { domain: "pinterest.com", answer: "Pinterest", accept: [], category: "Social Media" },
  { domain: "whatsapp.com", answer: "WhatsApp", accept: [], category: "Social Media" },
  { domain: "discord.com", answer: "Discord", accept: [], category: "Social Media" },
  { domain: "telegram.org", answer: "Telegram", accept: [], category: "Social Media" },
  { domain: "wechat.com", answer: "WeChat", accept: [], category: "Social Media" },
  { domain: "tumblr.com", answer: "Tumblr", accept: [], category: "Social Media" },
  { domain: "threads.net", answer: "Threads", accept: [], category: "Social Media" },
  { domain: "signal.org", answer: "Signal", accept: [], category: "Social Media" },
  { domain: "quora.com", answer: "Quora", accept: [], category: "Social Media" },
  { domain: "messenger.com", answer: "Messenger", accept: [], category: "Social Media" },
  { domain: "vimeo.com", answer: "Vimeo", accept: [], category: "Social Media" },
  { domain: "mastodon.social", answer: "Mastodon", accept: [], category: "Social Media" },
  { domain: "louisvuitton.com", answer: "Louis Vuitton", accept: ["lv"], category: "Luxury Brands" },
  { domain: "rolex.com", answer: "Rolex", accept: [], category: "Luxury Brands" },
  { domain: "gucci.com", answer: "Gucci", accept: [], category: "Luxury Brands" },
  { domain: "chanel.com", answer: "Chanel", accept: [], category: "Luxury Brands" },
  { domain: "prada.com", answer: "Prada", accept: [], category: "Luxury Brands" },
  { domain: "cartier.com", answer: "Cartier", accept: [], category: "Luxury Brands" },
  { domain: "hermes.com", answer: "Hermès", accept: ["hermes"], category: "Luxury Brands" },
  { domain: "tiffany.com", answer: "Tiffany & Co.", accept: ["tiffany", "tiffanys"], category: "Luxury Brands" },
  { domain: "burberry.com", answer: "Burberry", accept: [], category: "Luxury Brands" },
  { domain: "versace.com", answer: "Versace", accept: [], category: "Luxury Brands" },
  { domain: "dior.com", answer: "Dior", accept: [], category: "Luxury Brands" },
  { domain: "fendi.com", answer: "Fendi", accept: [], category: "Luxury Brands" },
  { domain: "balenciaga.com", answer: "Balenciaga", accept: [], category: "Luxury Brands" },
  { domain: "armani.com", answer: "Armani", accept: ["giorgio armani"], category: "Luxury Brands" },
  { domain: "dolcegabbana.com", answer: "Dolce & Gabbana", accept: ["dolce gabbana", "d and g"], category: "Luxury Brands" },
  { domain: "bulgari.com", answer: "Bulgari", accept: ["bvlgari"], category: "Luxury Brands" },
  { domain: "omegawatches.com", answer: "Omega", accept: [], category: "Luxury Brands" },
  { domain: "tagheuer.com", answer: "Tag Heuer", accept: [], category: "Luxury Brands" },
  { domain: "montblanc.com", answer: "Montblanc", accept: [], category: "Luxury Brands" },
  { domain: "ysl.com", answer: "Yves Saint Laurent", accept: ["ysl", "saint laurent"], category: "Luxury Brands" },
  { domain: "givenchy.com", answer: "Givenchy", accept: [], category: "Luxury Brands" },
  { domain: "valentino.com", answer: "Valentino", accept: [], category: "Luxury Brands" },
  { domain: "bottegaveneta.com", answer: "Bottega Veneta", accept: [], category: "Luxury Brands" },
  { domain: "patek.com", answer: "Patek Philippe", accept: ["patek philippe"], category: "Luxury Brands" },
  { domain: "airbnb.com", answer: "Airbnb", accept: [], category: "Travel & Hospitality" },
  { domain: "booking.com", answer: "Booking.com", accept: ["booking"], category: "Travel & Hospitality" },
  { domain: "expedia.com", answer: "Expedia", accept: [], category: "Travel & Hospitality" },
  { domain: "marriott.com", answer: "Marriott", accept: [], category: "Travel & Hospitality" },
  { domain: "hilton.com", answer: "Hilton", accept: [], category: "Travel & Hospitality" },
  { domain: "uber.com", answer: "Uber", accept: [], category: "Travel & Hospitality" },
  { domain: "lyft.com", answer: "Lyft", accept: [], category: "Travel & Hospitality" },
  { domain: "tripadvisor.com", answer: "Tripadvisor", accept: ["trip advisor"], category: "Travel & Hospitality" },
  { domain: "hyatt.com", answer: "Hyatt", accept: [], category: "Travel & Hospitality" },
  { domain: "ihg.com", answer: "Holiday Inn", accept: ["holiday inn", "ihg"], category: "Travel & Hospitality" },
  { domain: "ritzcarlton.com", answer: "Ritz-Carlton", accept: ["ritz carlton"], category: "Travel & Hospitality" },
  { domain: "fourseasons.com", answer: "Four Seasons", accept: [], category: "Travel & Hospitality" },
  { domain: "bestwestern.com", answer: "Best Western", accept: [], category: "Travel & Hospitality" },
  { domain: "radisson.com", answer: "Radisson", accept: [], category: "Travel & Hospitality" },
  { domain: "kayak.com", answer: "Kayak", accept: [], category: "Travel & Hospitality" },
  { domain: "trivago.com", answer: "Trivago", accept: [], category: "Travel & Hospitality" },
  { domain: "priceline.com", answer: "Priceline", accept: [], category: "Travel & Hospitality" },
  { domain: "agoda.com", answer: "Agoda", accept: [], category: "Travel & Hospitality" },
  { domain: "hostelworld.com", answer: "Hostelworld", accept: [], category: "Travel & Hospitality" },
  { domain: "vrbo.com", answer: "Vrbo", accept: [], category: "Travel & Hospitality" },
  { domain: "pg.com", answer: "Procter & Gamble", accept: ["p and g", "pg"], category: "Consumer Goods" },
  { domain: "unilever.com", answer: "Unilever", accept: [], category: "Consumer Goods" },
  { domain: "colgate.com", answer: "Colgate", accept: [], category: "Consumer Goods" },
  { domain: "gillette.com", answer: "Gillette", accept: [], category: "Consumer Goods" },
  { domain: "dove.com", answer: "Dove", accept: [], category: "Consumer Goods" },
  { domain: "nivea.com", answer: "Nivea", accept: [], category: "Consumer Goods" },
  { domain: "loreal.com", answer: "L'Oréal", accept: ["loreal"], category: "Consumer Goods" },
  { domain: "pampers.com", answer: "Pampers", accept: [], category: "Consumer Goods" },
  { domain: "tide.com", answer: "Tide", accept: [], category: "Consumer Goods" },
  { domain: "clorox.com", answer: "Clorox", accept: [], category: "Consumer Goods" },
  { domain: "lysol.com", answer: "Lysol", accept: [], category: "Consumer Goods" },
  { domain: "febreze.com", answer: "Febreze", accept: [], category: "Consumer Goods" },
  { domain: "oldspice.com", answer: "Old Spice", accept: [], category: "Consumer Goods" },
  { domain: "headandshoulders.com", answer: "Head & Shoulders", accept: ["head and shoulders"], category: "Consumer Goods" },
  { domain: "pantene.com", answer: "Pantene", accept: [], category: "Consumer Goods" },
  { domain: "vaseline.com", answer: "Vaseline", accept: [], category: "Consumer Goods" },
  { domain: "kleenex.com", answer: "Kleenex", accept: [], category: "Consumer Goods" },
  { domain: "huggies.com", answer: "Huggies", accept: [], category: "Consumer Goods" },
  { domain: "duracell.com", answer: "Duracell", accept: [], category: "Consumer Goods" },
  { domain: "energizer.com", answer: "Energizer", accept: [], category: "Consumer Goods" },
  { domain: "3m.com", answer: "3M", accept: [], category: "Consumer Goods" },
  { domain: "wd40.com", answer: "WD-40", accept: ["wd40"], category: "Consumer Goods" },
  { domain: "crest.com", answer: "Crest", accept: [], category: "Consumer Goods" },
  { domain: "listerine.com", answer: "Listerine", accept: [], category: "Consumer Goods" },
  { domain: "pfizer.com", answer: "Pfizer", accept: [], category: "Healthcare" },
  { domain: "jnj.com", answer: "Johnson & Johnson", accept: ["johnson and johnson", "j and j", "jnj"], category: "Healthcare" },
  { domain: "cvshealth.com", answer: "CVS Health", accept: ["cvs health"], category: "Healthcare" },
  { domain: "moderna.com", answer: "Moderna", accept: [], category: "Healthcare" },
  { domain: "bayer.com", answer: "Bayer", accept: [], category: "Healthcare" },
  { domain: "roche.com", answer: "Roche", accept: [], category: "Healthcare" },
  { domain: "novartis.com", answer: "Novartis", accept: [], category: "Healthcare" },
  { domain: "unitedhealthgroup.com", answer: "UnitedHealth", accept: ["united health"], category: "Healthcare" },
  { domain: "merck.com", answer: "Merck", accept: [], category: "Healthcare" },
  { domain: "astrazeneca.com", answer: "AstraZeneca", accept: [], category: "Healthcare" },
  { domain: "gsk.com", answer: "GSK", accept: ["glaxosmithkline"], category: "Healthcare" },
  { domain: "abbott.com", answer: "Abbott", accept: [], category: "Healthcare" },
  { domain: "medtronic.com", answer: "Medtronic", accept: [], category: "Healthcare" },
  { domain: "cigna.com", answer: "Cigna", accept: [], category: "Healthcare" },
  { domain: "aetna.com", answer: "Aetna", accept: [], category: "Healthcare" },
  { domain: "humana.com", answer: "Humana", accept: [], category: "Healthcare" },
  { domain: "kaiserpermanente.org", answer: "Kaiser Permanente", accept: ["kaiser"], category: "Healthcare" },
  { domain: "mayoclinic.org", answer: "Mayo Clinic", accept: [], category: "Healthcare" },
  { domain: "webmd.com", answer: "WebMD", accept: [], category: "Healthcare" },
  { domain: "teladoc.com", answer: "Teladoc", accept: [], category: "Healthcare" },
  { domain: "lilly.com", answer: "Eli Lilly", accept: ["lilly"], category: "Healthcare" },
];
