// ===========================================================================
// grader-content.js — "Are You Smarter Than a School Grader?" question bank.
// Only the HOST loads this file, so answers stay off players' devices.
// Organized by GRADE (1-5) -> SUBJECT -> array of { q, a:[4 options], c:correctIndex }.
// Grade-appropriate: Grade 1 is very basic, Grade 5 is upper-elementary.
// ===========================================================================
export const SUBJECTS = ["Math", "Science", "English", "Geography", "History"];
export const GRADES = [1, 2, 3, 4, 5];
export const GRADE_LABEL = { 1: "Grade 1", 2: "Grade 2", 3: "Grade 3", 4: "Grade 4", 5: "Grade 5" };

export const QUESTIONS = {
  1: {
    Math: [
      { q: "What is 2 + 3?", a: ["4", "5", "6", "7"], c: 1 },
      { q: "Which number is bigger, 7 or 4?", a: ["7", "4", "They are equal", "Neither"], c: 0 },
      { q: "How many sides does a triangle have?", a: ["2", "3", "4", "5"], c: 1 },
      { q: "What is 10 − 2?", a: ["6", "7", "8", "9"], c: 2 },
      { q: "What comes after the number 9?", a: ["8", "10", "11", "0"], c: 1 },
      { q: "How many fingers are on one hand?", a: ["4", "5", "6", "10"], c: 1 },
    ],
    Science: [
      { q: "What do plants need to grow?", a: ["Sunlight and water", "Candy", "Toys", "Darkness only"], c: 0 },
      { q: "What is a baby dog called?", a: ["Kitten", "Puppy", "Calf", "Cub"], c: 1 },
      { q: "Which one is a fruit?", a: ["Carrot", "Apple", "Potato", "Onion"], c: 1 },
      { q: "How many legs does a spider have?", a: ["6", "8", "4", "10"], c: 1 },
      { q: "What do we breathe in to stay alive?", a: ["Water", "Air", "Sand", "Milk"], c: 1 },
      { q: "Which animal says 'moo'?", a: ["Dog", "Cat", "Cow", "Duck"], c: 2 },
    ],
    English: [
      { q: "What is the opposite of 'hot'?", a: ["Warm", "Cold", "Fast", "Big"], c: 1 },
      { q: "Which letter is a vowel?", a: ["B", "C", "E", "T"], c: 2 },
      { q: "What is the plural of 'cat'?", a: ["Cat", "Cats", "Cates", "Catz"], c: 1 },
      { q: "Which word rhymes with 'dog'?", a: ["Cat", "Log", "Sun", "Hat"], c: 1 },
      { q: "What letter does 'apple' start with?", a: ["A", "E", "P", "L"], c: 0 },
      { q: "Which of these is a complete sentence?", a: ["The big", "Running fast", "I like dogs.", "Under the"], c: 2 },
    ],
    Geography: [
      { q: "What do we call the planet we live on?", a: ["Mars", "Earth", "Moon", "Sun"], c: 1 },
      { q: "What is a very large body of water called?", a: ["Puddle", "Ocean", "Cup", "Bath"], c: 1 },
      { q: "What do you call a place with lots of sand and very little water?", a: ["Forest", "Desert", "Lake", "City"], c: 1 },
      { q: "Which is bigger, a city or a house?", a: ["A house", "A city", "Same size", "Neither"], c: 1 },
      { q: "What do we call frozen water that falls from the sky?", a: ["Rain", "Snow", "Wind", "Fog"], c: 1 },
      { q: "Where do fish live?", a: ["In water", "In trees", "In the sky", "Underground"], c: 0 },
    ],
    History: [
      { q: "Which of these is a community helper?", a: ["Firefighter", "Dinosaur", "Robot toy", "Cloud"], c: 0 },
      { q: "What do we call the day you were born each year?", a: ["Holiday", "Birthday", "Weekend", "Monday"], c: 1 },
      { q: "What is the flag a symbol of?", a: ["A country", "A snack", "A game", "A song"], c: 0 },
      { q: "Who teaches you at school?", a: ["A teacher", "A chef", "A pilot", "A farmer"], c: 0 },
      { q: "What do we call people in your family who lived long before you?", a: ["Neighbors", "Ancestors", "Strangers", "Classmates"], c: 1 },
      { q: "Which is used to travel on water?", a: ["Boat", "Car", "Bicycle", "Train"], c: 0 },
    ],
  },
  2: {
    Math: [
      { q: "What is 6 + 7?", a: ["12", "13", "14", "11"], c: 1 },
      { q: "What is 5 × 2?", a: ["7", "10", "12", "25"], c: 1 },
      { q: "How many minutes are in one hour?", a: ["30", "60", "100", "24"], c: 1 },
      { q: "What is 20 − 8?", a: ["11", "12", "13", "14"], c: 1 },
      { q: "Which shape has four equal sides?", a: ["Triangle", "Square", "Circle", "Oval"], c: 1 },
      { q: "What number is the smallest?", a: ["15", "9", "23", "40"], c: 1 },
    ],
    Science: [
      { q: "How many legs does an insect have?", a: ["4", "6", "8", "10"], c: 1 },
      { q: "What is the closest star to Earth?", a: ["The Moon", "The Sun", "Mars", "Polaris"], c: 1 },
      { q: "Which of these is a mammal?", a: ["Snake", "Frog", "Dog", "Fish"], c: 2 },
      { q: "What are the three states of water?", a: ["Solid, liquid, gas", "Hot, warm, cold", "Big, small, tiny", "Red, blue, green"], c: 0 },
      { q: "What part of the plant is usually underground?", a: ["Leaf", "Flower", "Roots", "Stem"], c: 2 },
      { q: "What season comes after winter?", a: ["Summer", "Spring", "Fall", "Autumn"], c: 1 },
    ],
    English: [
      { q: "What do you call a word that means the same as another?", a: ["Antonym", "Synonym", "Verb", "Number"], c: 1 },
      { q: "Which word is a noun?", a: ["Run", "Happy", "Dog", "Quickly"], c: 2 },
      { q: "What punctuation ends a question?", a: ["Period", "Question mark", "Comma", "Colon"], c: 1 },
      { q: "What is the past tense of 'jump'?", a: ["Jumps", "Jumping", "Jumped", "Jump"], c: 2 },
      { q: "Which word is spelled correctly?", a: ["Frend", "Friend", "Freind", "Frennd"], c: 1 },
      { q: "A group of words that tells a complete idea is a?", a: ["Letter", "Sentence", "Sound", "Page"], c: 1 },
    ],
    Geography: [
      { q: "In which direction does the sun rise?", a: ["North", "South", "East", "West"], c: 2 },
      { q: "Which tool is used to find directions like north and south?", a: ["Ruler", "Compass", "Clock", "Scale"], c: 1 },
      { q: "How many continents are there on Earth?", a: ["5", "6", "7", "8"], c: 2 },
      { q: "What do we call a tall landform with a peak?", a: ["Valley", "Mountain", "Plain", "River"], c: 1 },
      { q: "What does a map show us?", a: ["The time of day", "Places and directions", "A song", "The temperature"], c: 1 },
      { q: "Which of these is a country?", a: ["Canada", "Africa", "Pacific", "Asia"], c: 0 },
    ],
    History: [
      { q: "Who was the first President of the United States?", a: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], c: 1 },
      { q: "What do we call a story passed down that may not be fully true?", a: ["Fact", "Legend", "Menu", "List"], c: 1 },
      { q: "What holiday celebrates the birth of the United States?", a: ["Halloween", "Independence Day", "Valentine's Day", "Labor Day"], c: 1 },
      { q: "Long ago, before cars, how did people often travel on land?", a: ["Airplanes", "Horses", "Rockets", "Submarines"], c: 1 },
      { q: "What are rules made by a government called?", a: ["Games", "Laws", "Songs", "Recipes"], c: 1 },
      { q: "What do we call writing that records what happened in the past?", a: ["Fiction", "History", "Poetry", "Music"], c: 1 },
    ],
  },
  3: {
    Math: [
      { q: "What is 7 × 6?", a: ["36", "42", "48", "40"], c: 1 },
      { q: "What is 100 ÷ 4?", a: ["20", "25", "30", "40"], c: 1 },
      { q: "How many degrees are in a right angle?", a: ["45", "90", "180", "360"], c: 1 },
      { q: "What fraction is the same as one half?", a: ["1/3", "2/4", "1/4", "3/4"], c: 1 },
      { q: "What is 345 rounded to the nearest ten?", a: ["340", "350", "300", "400"], c: 1 },
      { q: "How many sides does a hexagon have?", a: ["5", "6", "7", "8"], c: 1 },
    ],
    Science: [
      { q: "What gas do plants take in and use to make food?", a: ["Oxygen", "Carbon dioxide", "Helium", "Nitrogen"], c: 1 },
      { q: "What is the center of our solar system?", a: ["Earth", "The Moon", "The Sun", "Jupiter"], c: 2 },
      { q: "What do we call animals that eat only plants?", a: ["Carnivores", "Herbivores", "Omnivores", "Insectivores"], c: 1 },
      { q: "Which of these is a source of light?", a: ["A mirror", "The Sun", "A window", "A rock"], c: 1 },
      { q: "What is the hard part of your body that gives you shape?", a: ["Skin", "Skeleton", "Hair", "Blood"], c: 1 },
      { q: "What do we call water falling from clouds?", a: ["Evaporation", "Precipitation", "Condensation", "Reflection"], c: 1 },
    ],
    English: [
      { q: "What do you call a word that describes a noun?", a: ["Verb", "Adjective", "Adverb", "Pronoun"], c: 1 },
      { q: "What is the opposite (antonym) of 'ancient'?", a: ["Old", "Modern", "Huge", "Quiet"], c: 1 },
      { q: "Which word is a verb?", a: ["Table", "Blue", "Sing", "Slowly"], c: 2 },
      { q: "What is the contraction for 'do not'?", a: ["Dont", "Do'nt", "Don't", "Donot"], c: 2 },
      { q: "A word that sounds the same but is spelled differently (like 'to' and 'two') is a?", a: ["Synonym", "Homophone", "Prefix", "Suffix"], c: 1 },
      { q: "What is the main character in a story called?", a: ["Author", "Protagonist", "Reader", "Title"], c: 1 },
    ],
    Geography: [
      { q: "What is the largest ocean on Earth?", a: ["Atlantic", "Indian", "Pacific", "Arctic"], c: 2 },
      { q: "What imaginary line divides the Earth into north and south halves?", a: ["Prime Meridian", "Equator", "Tropic", "Axis"], c: 1 },
      { q: "What is the capital of the United States?", a: ["New York", "Washington, D.C.", "Los Angeles", "Chicago"], c: 1 },
      { q: "On which continent is Egypt located?", a: ["Asia", "Europe", "Africa", "Australia"], c: 2 },
      { q: "What do we call a small piece of land surrounded by water?", a: ["Peninsula", "Island", "Bay", "Cape"], c: 1 },
      { q: "Which of these is a natural resource?", a: ["Plastic", "Water", "Glass", "Paper"], c: 1 },
    ],
    History: [
      { q: "Who is often credited with reaching the Americas in 1492?", a: ["Columbus", "Magellan", "Lincoln", "Edison"], c: 0 },
      { q: "What large structure in China is thousands of miles long?", a: ["The Colosseum", "The Great Wall", "The Pyramids", "The Eiffel Tower"], c: 1 },
      { q: "What do we call the study of very old objects dug from the ground?", a: ["Biology", "Archaeology", "Astronomy", "Geometry"], c: 1 },
      { q: "Ancient Egyptians built giant stone structures called?", a: ["Castles", "Pyramids", "Skyscrapers", "Bridges"], c: 1 },
      { q: "What document begins 'We the People'?", a: ["The U.S. Constitution", "A grocery list", "A comic book", "A phone book"], c: 0 },
      { q: "What were knights known for wearing in battle?", a: ["Togas", "Armor", "Pajamas", "Raincoats"], c: 1 },
    ],
  },
  4: {
    Math: [
      { q: "What is 8 × 7?", a: ["54", "56", "63", "48"], c: 1 },
      { q: "What is 6 × 9 − 4?", a: ["50", "45", "58", "54"], c: 0 },
      { q: "What is 3/5 of 25?", a: ["10", "15", "20", "12"], c: 1 },
      { q: "Which of these is a prime number?", a: ["21", "15", "13", "27"], c: 2 },
      { q: "What is 1,000 − 250 − 125?", a: ["625", "725", "615", "750"], c: 0 },
      { q: "What is 144 ÷ 12?", a: ["12", "14", "11", "16"], c: 0 },
    ],
    Science: [
      { q: "What is the powerhouse of the cell?", a: ["Nucleus", "Mitochondria", "Ribosome", "Membrane"], c: 1 },
      { q: "Which planet is known as the Red Planet?", a: ["Venus", "Mars", "Jupiter", "Mercury"], c: 1 },
      { q: "What force pulls objects toward the Earth?", a: ["Magnetism", "Gravity", "Friction", "Tension"], c: 1 },
      { q: "What is the process by which plants make food using sunlight?", a: ["Respiration", "Photosynthesis", "Digestion", "Evaporation"], c: 1 },
      { q: "How many bones does an adult human have?", a: ["106", "206", "306", "406"], c: 1 },
      { q: "What type of animal is cold-blooded and has scales?", a: ["Mammal", "Reptile", "Bird", "Insect"], c: 1 },
    ],
    English: [
      { q: "What is a comparison using 'like' or 'as' called?", a: ["Metaphor", "Simile", "Hyperbole", "Pun"], c: 1 },
      { q: "What is the prefix in the word 'unhappy'?", a: ["un", "happy", "py", "ha"], c: 0 },
      { q: "Which sentence uses correct punctuation?", a: ["where are you", "Where are you?", "Where are you.", "where are you!"], c: 1 },
      { q: "What part of speech is the word 'quickly'?", a: ["Noun", "Verb", "Adjective", "Adverb"], c: 3 },
      { q: "What is the plural of 'mouse' (the animal)?", a: ["Mouses", "Mice", "Mouse", "Meese"], c: 1 },
      { q: "What do you call the person who writes a book?", a: ["Editor", "Author", "Publisher", "Narrator"], c: 1 },
    ],
    Geography: [
      { q: "What is the capital of Canada?", a: ["Toronto", "Ottawa", "Vancouver", "Montreal"], c: 1 },
      { q: "What is the largest continent by area?", a: ["Africa", "Asia", "Europe", "North America"], c: 1 },
      { q: "Which river flows through Egypt?", a: ["Amazon", "Nile", "Ganges", "Danube"], c: 1 },
      { q: "Mount Everest lies in which mountain range?", a: ["Andes", "Alps", "Himalayas", "Rockies"], c: 2 },
      { q: "Which U.S. state is the largest by area?", a: ["Texas", "California", "Alaska", "Montana"], c: 2 },
      { q: "How many Great Lakes are there?", a: ["3", "4", "5", "6"], c: 2 },
    ],
    History: [
      { q: "Who was President during the American Civil War?", a: ["George Washington", "Abraham Lincoln", "Theodore Roosevelt", "John Adams"], c: 1 },
      { q: "In what year did World War II end?", a: ["1918", "1939", "1945", "1950"], c: 2 },
      { q: "The ancient Olympic Games began in which country?", a: ["Italy", "Egypt", "Greece", "China"], c: 2 },
      { q: "Who was the famous nurse known for helping soldiers and founding modern nursing?", a: ["Florence Nightingale", "Marie Curie", "Rosa Parks", "Amelia Earhart"], c: 0 },
      { q: "What ship sank in 1912 after hitting an iceberg?", a: ["Mayflower", "Titanic", "Santa Maria", "Lusitania"], c: 1 },
      { q: "The Declaration of Independence was signed in which year?", a: ["1707", "1776", "1812", "1865"], c: 1 },
    ],
  },
  5: {
    Math: [
      { q: "What is the square root of 169?", a: ["12", "13", "14", "15"], c: 1 },
      { q: "Solve using order of operations: 8 + 4 × 3", a: ["36", "20", "24", "14"], c: 1 },
      { q: "What is 40% of 150?", a: ["45", "60", "75", "50"], c: 1 },
      { q: "What is 7³ (7 cubed)?", a: ["49", "147", "343", "721"], c: 2 },
      { q: "What is 2/3 of 90?", a: ["45", "60", "30", "120"], c: 1 },
      { q: "What is 15 × 12?", a: ["170", "180", "150", "210"], c: 1 },
    ],
    Science: [
      { q: "What is the chemical symbol for water?", a: ["CO2", "H2O", "O2", "NaCl"], c: 1 },
      { q: "What is the largest planet in our solar system?", a: ["Saturn", "Earth", "Jupiter", "Neptune"], c: 2 },
      { q: "What do we call an animal that eats both plants and meat?", a: ["Herbivore", "Carnivore", "Omnivore", "Producer"], c: 2 },
      { q: "What gas makes up most of Earth's atmosphere?", a: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], c: 1 },
      { q: "What is the boiling point of water in Celsius at sea level?", a: ["50°C", "90°C", "100°C", "212°C"], c: 2 },
      { q: "Which part of the body pumps blood?", a: ["Lungs", "Brain", "Heart", "Liver"], c: 2 },
    ],
    English: [
      { q: "What is an exaggeration for effect (e.g., 'I've told you a million times') called?", a: ["Simile", "Hyperbole", "Metaphor", "Idiom"], c: 1 },
      { q: "Which sentence is written in the passive voice?", a: ["The dog chased the ball.", "The ball was chased by the dog.", "Chase the ball!", "The dog runs fast."], c: 1 },
      { q: "What is the suffix in the word 'careful'?", a: ["care", "ful", "ca", "ful care"], c: 1 },
      { q: "What do you call the turning point or most exciting part of a story?", a: ["Setting", "Climax", "Prologue", "Index"], c: 1 },
      { q: "Which word is a conjunction?", a: ["Because", "Table", "Green", "Slowly"], c: 0 },
      { q: "A word that means the opposite of another is a(n)?", a: ["Synonym", "Antonym", "Homophone", "Acronym"], c: 1 },
    ],
    Geography: [
      { q: "What is the smallest country in the world?", a: ["Monaco", "Vatican City", "San Marino", "Malta"], c: 1 },
      { q: "What is the capital of Australia?", a: ["Sydney", "Melbourne", "Canberra", "Perth"], c: 2 },
      { q: "What is the capital of Brazil?", a: ["Rio de Janeiro", "São Paulo", "Brasília", "Buenos Aires"], c: 2 },
      { q: "The Sahara Desert is located on which continent?", a: ["Asia", "Australia", "Africa", "South America"], c: 2 },
      { q: "What is the capital of Turkey?", a: ["Istanbul", "Ankara", "Izmir", "Bursa"], c: 1 },
      { q: "Which two continents does the Ural range separate?", a: ["Africa and Asia", "Europe and Asia", "Europe and Africa", "Asia and Australia"], c: 1 },
    ],
    History: [
      { q: "Who wrote the Declaration of Independence's first draft?", a: ["George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"], c: 1 },
      { q: "Which ancient civilization built Machu Picchu?", a: ["Aztec", "Maya", "Inca", "Roman"], c: 2 },
      { q: "Who led the nonviolent movement for India's independence?", a: ["Nelson Mandela", "Mahatma Gandhi", "Martin Luther King Jr.", "Winston Churchill"], c: 1 },
      { q: "The U.S. Civil War was mainly fought over which issue?", a: ["Taxes on tea", "Slavery", "Land in Canada", "Oil"], c: 1 },
      { q: "Who was the first man to walk on the Moon?", a: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"], c: 2 },
      { q: "In which country did the Renaissance begin?", a: ["France", "England", "Italy", "Spain"], c: 2 },
    ],
  },
};
