// ===========================================================================
// grader-content.js — "Are You Smarter Than a School Grader?" question bank.
// Only the HOST loads this file, so answers stay off players' devices.
// Organized by GRADE (1-5) -> SUBJECT -> array of { q, a:[4 options], c:correctIndex }.
// Grade-appropriate: Grade 1 is very basic, Grade 5 is upper-elementary.
// ===========================================================================
export const SUBJECTS = ["Math", "Science", "English", "Geography", "History"];
export const GRADES = [1, 2, 3, 4, 5, 6, 7, 8];
export const GRADE_LABEL = { 1: "Grade 1", 2: "Grade 2", 3: "Grade 3", 4: "Grade 4", 5: "Grade 5", 6: "Grade 6", 7: "Grade 7", 8: "Grade 8" };

export const QUESTIONS = {
  1: {
    Math: [
      { q: "What is 2 + 3?", a: ["4", "5", "6", "7"], c: 1 },
      { q: "Which number is bigger, 7 or 4?", a: ["7", "4", "They are equal", "Neither"], c: 0 },
      { q: "How many sides does a triangle have?", a: ["2", "3", "4", "5"], c: 1 },
      { q: "What is 10 − 2?", a: ["6", "7", "8", "9"], c: 2 },
      { q: "What comes after the number 9?", a: ["8", "10", "11", "0"], c: 1 },
      { q: "How many fingers are on one hand?", a: ["4", "5", "6", "10"], c: 1 },
    ],
    Science: [
      { q: "What do plants need to grow?", a: ["Sunlight and water", "Candy", "Toys", "Darkness only"], c: 0 },
      { q: "What is a baby dog called?", a: ["Kitten", "Puppy", "Calf", "Cub"], c: 1 },
      { q: "Which one is a fruit?", a: ["Carrot", "Apple", "Potato", "Onion"], c: 1 },
      { q: "How many legs does a spider have?", a: ["6", "8", "4", "10"], c: 1 },
      { q: "What do we breathe in to stay alive?", a: ["Water", "Air", "Sand", "Milk"], c: 1 },
      { q: "Which animal says 'moo'?", a: ["Dog", "Cat", "Cow", "Duck"], c: 2 },
    ],
    English: [
      { q: "What is the opposite of 'hot'?", a: ["Warm", "Cold", "Fast", "Big"], c: 1 },
      { q: "Which letter is a vowel?", a: ["B", "C", "E", "T"], c: 2 },
      { q: "What is the plural of 'cat'?", a: ["Cat", "Cats", "Cates", "Catz"], c: 1 },
      { q: "Which word rhymes with 'dog'?", a: ["Cat", "Log", "Sun", "Hat"], c: 1 },
      { q: "What letter does 'apple' start with?", a: ["A", "E", "P", "L"], c: 0 },
      { q: "Which of these is a complete sentence?", a: ["The big", "Running fast", "I like dogs.", "Under the"], c: 2 },
    ],
    Geography: [
      { q: "What do we call the planet we live on?", a: ["Mars", "Earth", "Moon", "Sun"], c: 1 },
      { q: "What is a very large body of water called?", a: ["Puddle", "Ocean", "Cup", "Bath"], c: 1 },
      { q: "What do you call a place with lots of sand and very little water?", a: ["Forest", "Desert", "Lake", "City"], c: 1 },
      { q: "Which is bigger, a city or a house?", a: ["A house", "A city", "Same size", "Neither"], c: 1 },
      { q: "What do we call frozen water that falls from the sky?", a: ["Rain", "Snow", "Wind", "Fog"], c: 1 },
      { q: "Where do fish live?", a: ["In water", "In trees", "In the sky", "Underground"], c: 0 },
    ],
    History: [
      { q: "Which of these is a community helper?", a: ["Firefighter", "Dinosaur", "Robot toy", "Cloud"], c: 0 },
      { q: "What do we call the day you were born each year?", a: ["Holiday", "Birthday", "Weekend", "Monday"], c: 1 },
      { q: "What is the flag a symbol of?", a: ["A country", "A snack", "A game", "A song"], c: 0 },
      { q: "Who teaches you at school?", a: ["A teacher", "A chef", "A pilot", "A farmer"], c: 0 },
      { q: "What do we call people in your family who lived long before you?", a: ["Neighbors", "Ancestors", "Strangers", "Classmates"], c: 1 },
      { q: "Which is used to travel on water?", a: ["Boat", "Car", "Bicycle", "Train"], c: 0 },
    ],
  },
  2: {
    Math: [
      { q: "What is 6 + 7?", a: ["12", "13", "14", "11"], c: 1 },
      { q: "What is 5 × 2?", a: ["7", "10", "12", "25"], c: 1 },
      { q: "How many minutes are in one hour?", a: ["30", "60", "100", "24"], c: 1 },
      { q: "What is 20 − 8?", a: ["11", "12", "13", "14"], c: 1 },
      { q: "Which shape has four equal sides?", a: ["Triangle", "Square", "Circle", "Oval"], c: 1 },
      { q: "What number is the smallest?", a: ["15", "9", "23", "40"], c: 1 },
    ],
    Science: [
      { q: "How many legs does an insect have?", a: ["4", "6", "8", "10"], c: 1 },
      { q: "What is the closest star to Earth?", a: ["The Moon", "The Sun", "Mars", "Polaris"], c: 1 },
      { q: "Which of these is a mammal?", a: ["Snake", "Frog", "Dog", "Fish"], c: 2 },
      { q: "What are the three states of water?", a: ["Solid, liquid, gas", "Hot, warm, cold", "Big, small, tiny", "Red, blue, green"], c: 0 },
      { q: "What part of the plant is usually underground?", a: ["Leaf", "Flower", "Roots", "Stem"], c: 2 },
      { q: "What season comes after winter?", a: ["Summer", "Spring", "Fall", "Autumn"], c: 1 },
    ],
    English: [
      { q: "What do you call a word that means the same as another?", a: ["Antonym", "Synonym", "Verb", "Number"], c: 1 },
      { q: "Which word is a noun?", a: ["Run", "Happy", "Dog", "Quickly"], c: 2 },
      { q: "What punctuation ends a question?", a: ["Period", "Question mark", "Comma", "Colon"], c: 1 },
      { q: "What is the past tense of 'jump'?", a: ["Jumps", "Jumping", "Jumped", "Jump"], c: 2 },
      { q: "Which word is spelled correctly?", a: ["Frend", "Friend", "Freind", "Frennd"], c: 1 },
      { q: "A group of words that tells a complete idea is a?", a: ["Letter", "Sentence", "Sound", "Page"], c: 1 },
    ],
    Geography: [
      { q: "In which direction does the sun rise?", a: ["North", "South", "East", "West"], c: 2 },
      { q: "Which tool is used to find directions like north and south?", a: ["Ruler", "Compass", "Clock", "Scale"], c: 1 },
      { q: "How many continents are there on Earth?", a: ["5", "6", "7", "8"], c: 2 },
      { q: "What do we call a tall landform with a peak?", a: ["Valley", "Mountain", "Plain", "River"], c: 1 },
      { q: "What does a map show us?", a: ["The time of day", "Places and directions", "A song", "The temperature"], c: 1 },
      { q: "Which of these is a country?", a: ["Canada", "Africa", "Pacific", "Asia"], c: 0 },
    ],
    History: [
      { q: "Who was the first President of the United States?", a: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], c: 1 },
      { q: "What do we call a story passed down that may not be fully true?", a: ["Fact", "Legend", "Menu", "List"], c: 1 },
      { q: "What holiday celebrates the birth of the United States?", a: ["Halloween", "Independence Day", "Valentine's Day", "Labor Day"], c: 1 },
      { q: "Long ago, before cars, how did people often travel on land?", a: ["Airplanes", "Horses", "Rockets", "Submarines"], c: 1 },
      { q: "What are rules made by a government called?", a: ["Games", "Laws", "Songs", "Recipes"], c: 1 },
      { q: "What do we call writing that records what happened in the past?", a: ["Fiction", "History", "Poetry", "Music"], c: 1 },
    ],
  },
  3: {
    Math: [
      { q: "What is 7 × 6?", a: ["36", "42", "48", "40"], c: 1 },
      { q: "What is 100 ÷ 4?", a: ["20", "25", "30", "40"], c: 1 },
      { q: "How many degrees are in a right angle?", a: ["45", "90", "180", "360"], c: 1 },
      { q: "What fraction is the same as one half?", a: ["1/3", "2/4", "1/4", "3/4"], c: 1 },
      { q: "What is 345 rounded to the nearest ten?", a: ["340", "350", "300", "400"], c: 1 },
      { q: "How many sides does a hexagon have?", a: ["5", "6", "7", "8"], c: 1 },
    ],
    Science: [
      { q: "What gas do plants take in and use to make food?", a: ["Oxygen", "Carbon dioxide", "Helium", "Nitrogen"], c: 1 },
      { q: "What is the center of our solar system?", a: ["Earth", "The Moon", "The Sun", "Jupiter"], c: 2 },
      { q: "What do we call animals that eat only plants?", a: ["Carnivores", "Herbivores", "Omnivores", "Insectivores"], c: 1 },
      { q: "Which of these is a source of light?", a: ["A mirror", "The Sun", "A window", "A rock"], c: 1 },
      { q: "What is the hard part of your body that gives you shape?", a: ["Skin", "Skeleton", "Hair", "Blood"], c: 1 },
      { q: "What do we call water falling from clouds?", a: ["Evaporation", "Precipitation", "Condensation", "Reflection"], c: 1 },
    ],
    English: [
      { q: "What do you call a word that describes a noun?", a: ["Verb", "Adjective", "Adverb", "Pronoun"], c: 1 },
      { q: "What is the opposite (antonym) of 'ancient'?", a: ["Old", "Modern", "Huge", "Quiet"], c: 1 },
      { q: "Which word is a verb?", a: ["Table", "Blue", "Sing", "Slowly"], c: 2 },
      { q: "What is the contraction for 'do not'?", a: ["Dont", "Do'nt", "Don't", "Donot"], c: 2 },
      { q: "A word that sounds the same but is spelled differently (like 'to' and 'two') is a?", a: ["Synonym", "Homophone", "Prefix", "Suffix"], c: 1 },
      { q: "What is the main character in a story called?", a: ["Author", "Protagonist", "Reader", "Title"], c: 1 },
    ],
    Geography: [
      { q: "What is the largest ocean on Earth?", a: ["Atlantic", "Indian", "Pacific", "Arctic"], c: 2 },
      { q: "What imaginary line divides the Earth into north and south halves?", a: ["Prime Meridian", "Equator", "Tropic", "Axis"], c: 1 },
      { q: "What is the capital of the United States?", a: ["New York", "Washington, D.C.", "Los Angeles", "Chicago"], c: 1 },
      { q: "On which continent is Egypt located?", a: ["Asia", "Europe", "Africa", "Australia"], c: 2 },
      { q: "What do we call a small piece of land surrounded by water?", a: ["Peninsula", "Island", "Bay", "Cape"], c: 1 },
      { q: "Which of these is a natural resource?", a: ["Plastic", "Water", "Glass", "Paper"], c: 1 },
    ],
    History: [
      { q: "Who is often credited with reaching the Americas in 1492?", a: ["Columbus", "Magellan", "Lincoln", "Edison"], c: 0 },
      { q: "What large structure in China is thousands of miles long?", a: ["The Colosseum", "The Great Wall", "The Pyramids", "The Eiffel Tower"], c: 1 },
      { q: "What do we call the study of very old objects dug from the ground?", a: ["Biology", "Archaeology", "Astronomy", "Geometry"], c: 1 },
      { q: "Ancient Egyptians built giant stone structures called?", a: ["Castles", "Pyramids", "Skyscrapers", "Bridges"], c: 1 },
      { q: "What document begins 'We the People'?", a: ["The U.S. Constitution", "A grocery list", "A comic book", "A phone book"], c: 0 },
      { q: "What were knights known for wearing in battle?", a: ["Togas", "Armor", "Pajamas", "Raincoats"], c: 1 },
    ],
  },
  4: {
    Math: [
      { q: "What is 8 × 7?", a: ["54", "56", "63", "48"], c: 1 },
      { q: "What is 6 × 9 − 4?", a: ["50", "45", "58", "54"], c: 0 },
      { q: "What is 3/5 of 25?", a: ["10", "15", "20", "12"], c: 1 },
      { q: "Which of these is a prime number?", a: ["21", "15", "13", "27"], c: 2 },
      { q: "What is 1,000 − 250 − 125?", a: ["625", "725", "615", "750"], c: 0 },
      { q: "What is 144 ÷ 12?", a: ["12", "14", "11", "16"], c: 0 },
    ],
    Science: [
      { q: "What is the powerhouse of the cell?", a: ["Nucleus", "Mitochondria", "Ribosome", "Membrane"], c: 1 },
      { q: "Which planet is known as the Red Planet?", a: ["Venus", "Mars", "Jupiter", "Mercury"], c: 1 },
      { q: "What force pulls objects toward the Earth?", a: ["Magnetism", "Gravity", "Friction", "Tension"], c: 1 },
      { q: "What is the process by which plants make food using sunlight?", a: ["Respiration", "Photosynthesis", "Digestion", "Evaporation"], c: 1 },
      { q: "How many bones does an adult human have?", a: ["106", "206", "306", "406"], c: 1 },
      { q: "What type of animal is cold-blooded and has scales?", a: ["Mammal", "Reptile", "Bird", "Insect"], c: 1 },
    ],
    English: [
      { q: "What is a comparison using 'like' or 'as' called?", a: ["Metaphor", "Simile", "Hyperbole", "Pun"], c: 1 },
      { q: "What is the prefix in the word 'unhappy'?", a: ["un", "happy", "py", "ha"], c: 0 },
      { q: "Which sentence uses correct punctuation?", a: ["where are you", "Where are you?", "Where are you.", "where are you!"], c: 1 },
      { q: "What part of speech is the word 'quickly'?", a: ["Noun", "Verb", "Adjective", "Adverb"], c: 3 },
      { q: "What is the plural of 'mouse' (the animal)?", a: ["Mouses", "Mice", "Mouse", "Meese"], c: 1 },
      { q: "What do you call the person who writes a book?", a: ["Editor", "Author", "Publisher", "Narrator"], c: 1 },
    ],
    Geography: [
      { q: "What is the capital of Canada?", a: ["Toronto", "Ottawa", "Vancouver", "Montreal"], c: 1 },
      { q: "What is the largest continent by area?", a: ["Africa", "Asia", "Europe", "North America"], c: 1 },
      { q: "Which river flows through Egypt?", a: ["Amazon", "Nile", "Ganges", "Danube"], c: 1 },
      { q: "Mount Everest lies in which mountain range?", a: ["Andes", "Alps", "Himalayas", "Rockies"], c: 2 },
      { q: "Which U.S. state is the largest by area?", a: ["Texas", "California", "Alaska", "Montana"], c: 2 },
      { q: "How many Great Lakes are there?", a: ["3", "4", "5", "6"], c: 2 },
    ],
    History: [
      { q: "Who was President during the American Civil War?", a: ["George Washington", "Abraham Lincoln", "Theodore Roosevelt", "John Adams"], c: 1 },
      { q: "In what year did World War II end?", a: ["1918", "1939", "1945", "1950"], c: 2 },
      { q: "The ancient Olympic Games began in which country?", a: ["Italy", "Egypt", "Greece", "China"], c: 2 },
      { q: "Who was the famous nurse known for helping soldiers and founding modern nursing?", a: ["Florence Nightingale", "Marie Curie", "Rosa Parks", "Amelia Earhart"], c: 0 },
      { q: "What ship sank in 1912 after hitting an iceberg?", a: ["Mayflower", "Titanic", "Santa Maria", "Lusitania"], c: 1 },
      { q: "The Declaration of Independence was signed in which year?", a: ["1707", "1776", "1812", "1865"], c: 1 },
    ],
  },
  5: {
    Math: [
      { q: "What is the square root of 169?", a: ["12", "13", "14", "15"], c: 1 },
      { q: "Solve using order of operations: 8 + 4 × 3", a: ["36", "20", "24", "14"], c: 1 },
      { q: "What is 40% of 150?", a: ["45", "60", "75", "50"], c: 1 },
      { q: "What is 7³ (7 cubed)?", a: ["49", "147", "343", "721"], c: 2 },
      { q: "What is 2/3 of 90?", a: ["45", "60", "30", "120"], c: 1 },
      { q: "What is 15 × 12?", a: ["170", "180", "150", "210"], c: 1 },
    ],
    Science: [
      { q: "What is the chemical symbol for water?", a: ["CO2", "H2O", "O2", "NaCl"], c: 1 },
      { q: "What is the chemical symbol for gold?", a: ["Gd", "Au", "Go", "Ag"], c: 1 },
      { q: "What do we call an animal that eats both plants and meat?", a: ["Herbivore", "Carnivore", "Omnivore", "Producer"], c: 2 },
      { q: "What gas makes up most of Earth's atmosphere?", a: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], c: 1 },
      { q: "What type of rock forms from cooled magma or lava?", a: ["Sedimentary", "Igneous", "Metamorphic", "Fossil"], c: 1 },
      { q: "How many chambers does the human heart have?", a: ["2", "3", "4", "6"], c: 2 },
    ],
    English: [
      { q: "What is an exaggeration for effect (e.g., 'I've told you a million times') called?", a: ["Simile", "Hyperbole", "Metaphor", "Idiom"], c: 1 },
      { q: "Which sentence is written in the passive voice?", a: ["The dog chased the ball.", "The ball was chased by the dog.", "Chase the ball!", "The dog runs fast."], c: 1 },
      { q: "What is the suffix in the word 'careful'?", a: ["care", "ful", "ca", "ful care"], c: 1 },
      { q: "What do you call the turning point or most exciting part of a story?", a: ["Setting", "Climax", "Prologue", "Index"], c: 1 },
      { q: "Which word is a conjunction?", a: ["Because", "Table", "Green", "Slowly"], c: 0 },
      { q: "A word that means the opposite of another is a(n)?", a: ["Synonym", "Antonym", "Homophone", "Acronym"], c: 1 },
    ],
    Geography: [
      { q: "What is the smallest country in the world?", a: ["Monaco", "Vatican City", "San Marino", "Malta"], c: 1 },
      { q: "What is the capital of Australia?", a: ["Sydney", "Melbourne", "Canberra", "Perth"], c: 2 },
      { q: "What is the capital of Brazil?", a: ["Rio de Janeiro", "São Paulo", "Brasília", "Buenos Aires"], c: 2 },
      { q: "The Sahara Desert is located on which continent?", a: ["Asia", "Australia", "Africa", "South America"], c: 2 },
      { q: "What is the capital of Turkey?", a: ["Istanbul", "Ankara", "Izmir", "Bursa"], c: 1 },
      { q: "Which two continents does the Ural range separate?", a: ["Africa and Asia", "Europe and Asia", "Europe and Africa", "Asia and Australia"], c: 1 },
    ],
    History: [
      { q: "Who wrote the Declaration of Independence's first draft?", a: ["George Washington", "Thomas Jefferson", "Benjamin Franklin", "John Adams"], c: 1 },
      { q: "Which ancient civilization built Machu Picchu?", a: ["Aztec", "Maya", "Inca", "Roman"], c: 2 },
      { q: "Who led the nonviolent movement for India's independence?", a: ["Nelson Mandela", "Mahatma Gandhi", "Martin Luther King Jr.", "Winston Churchill"], c: 1 },
      { q: "The U.S. Civil War was mainly fought over which issue?", a: ["Taxes on tea", "Slavery", "Land in Canada", "Oil"], c: 1 },
      { q: "Who was the first man to walk on the Moon?", a: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"], c: 2 },
      { q: "In which country did the Renaissance begin?", a: ["France", "England", "Italy", "Spain"], c: 2 },
    ],
  },
  6: {
    Math: [
      { q: "Solve for x: 3x + 7 = 22.", a: ["3", "5", "7", "15"], c: 1 },
      { q: "What is the least common multiple (LCM) of 6 and 8?", a: ["24", "48", "12", "14"], c: 0 },
      { q: "What is 3⁴ (3 to the power of 4)?", a: ["12", "64", "81", "27"], c: 2 },
      { q: "A $40 shirt is 25% off. What is the sale price?", a: ["$30", "$35", "$10", "$25"], c: 0 },
      { q: "What is the greatest common factor (GCF) of 12 and 18?", a: ["3", "6", "9", "12"], c: 1 },
    ],
    Science: [
      { q: "What is the powerhouse of the cell?", a: ["Nucleus", "Ribosome", "Mitochondria", "Vacuole"], c: 2 },
      { q: "Which blood cells help fight infection?", a: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], c: 1 },
      { q: "How many bones are in the adult human body?", a: ["201", "206", "212", "198"], c: 1 },
      { q: "What is the pH of a neutral solution?", a: ["0", "7", "14", "1"], c: 1 },
      { q: "What process do plants use to make food from sunlight?", a: ["Respiration", "Photosynthesis", "Digestion", "Fermentation"], c: 1 },
    ],
    English: [
      { q: "In 'She sings beautifully,' what part of speech is 'beautifully'?", a: ["Adjective", "Adverb", "Verb", "Noun"], c: 1 },
      { q: "What is the plural of 'goose'?", a: ["Gooses", "Geese", "Goosen", "Geeses"], c: 1 },
      { q: "A group of words containing a subject and a verb is called a?", a: ["Phrase", "Clause", "Fragment", "Prefix"], c: 1 },
      { q: "Which word is a preposition?", a: ["Quickly", "Beneath", "Happy", "Jump"], c: 1 },
      { q: "What punctuation joins two independent clauses without a conjunction?", a: ["Comma", "Semicolon", "Colon", "Hyphen"], c: 1 },
    ],
    Geography: [
      { q: "Which is the longest river in the world?", a: ["Amazon", "Nile", "Yangtze", "Mississippi"], c: 1 },
      { q: "Mount Kilimanjaro is located in which country?", a: ["Kenya", "Tanzania", "Ethiopia", "Uganda"], c: 1 },
      { q: "What is the capital of Egypt?", a: ["Cairo", "Alexandria", "Giza", "Luxor"], c: 0 },
      { q: "Which is the largest ocean on Earth?", a: ["Atlantic", "Indian", "Pacific", "Arctic"], c: 2 },
      { q: "The Great Barrier Reef lies off the coast of which country?", a: ["Brazil", "Australia", "Mexico", "Indonesia"], c: 1 },
    ],
    History: [
      { q: "Which ancient civilization built the pyramids of Giza?", a: ["Romans", "Greeks", "Egyptians", "Persians"], c: 2 },
      { q: "Who was the last active pharaoh of ancient Egypt, allied with Rome?", a: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"], c: 1 },
      { q: "The ancient Olympic Games originated in which country?", a: ["Italy", "Greece", "Egypt", "Turkey"], c: 1 },
      { q: "Which empire was ruled by Julius Caesar?", a: ["Greek", "Roman", "Ottoman", "Mongol"], c: 1 },
      { q: "The Great Wall was built to protect which ancient country?", a: ["Japan", "China", "India", "Persia"], c: 1 },
    ],
  },
  7: {
    Math: [
      { q: "Solve for x: 5x − 3 = 2x + 12.", a: ["3", "5", "7", "15"], c: 1 },
      { q: "What is (−6) × (−4)?", a: ["−24", "24", "−10", "10"], c: 1 },
      { q: "What is the area of a triangle with base 10 and height 6?", a: ["60", "30", "16", "32"], c: 1 },
      { q: "What is the value of 5! (5 factorial)?", a: ["25", "120", "60", "20"], c: 1 },
      { q: "What is ¾ ÷ ½?", a: ["3/8", "1.5", "2/3", "1/4"], c: 1 },
    ],
    Science: [
      { q: "What is the chemical symbol for sodium?", a: ["So", "Na", "S", "Sd"], c: 1 },
      { q: "How many protons does a carbon atom have?", a: ["4", "6", "8", "12"], c: 1 },
      { q: "Which subatomic particle carries a negative charge?", a: ["Proton", "Neutron", "Electron", "Nucleus"], c: 2 },
      { q: "At sea level, water boils at what temperature in Fahrenheit?", a: ["100°F", "180°F", "212°F", "32°F"], c: 2 },
      { q: "What is the most common state of matter in the universe?", a: ["Solid", "Liquid", "Gas", "Plasma"], c: 3 },
    ],
    English: [
      { q: "Giving human traits to non-human things is called?", a: ["Hyperbole", "Personification", "Onomatopoeia", "Irony"], c: 1 },
      { q: "What is the repetition of initial consonant sounds called?", a: ["Assonance", "Alliteration", "Rhyme", "Meter"], c: 1 },
      { q: "Which word means 'to make something less severe'?", a: ["Aggravate", "Mitigate", "Amplify", "Provoke"], c: 1 },
      { q: "A word that imitates a sound (e.g., 'buzz') is an example of?", a: ["Metaphor", "Onomatopoeia", "Pun", "Idiom"], c: 1 },
      { q: "What is the term for the main character of a story?", a: ["Antagonist", "Protagonist", "Narrator", "Foil"], c: 1 },
    ],
    Geography: [
      { q: "What is the capital of Switzerland?", a: ["Zurich", "Geneva", "Bern", "Basel"], c: 2 },
      { q: "Which strait separates Europe and Asia in Turkey?", a: ["Gibraltar", "Bosphorus", "Hormuz", "Malacca"], c: 1 },
      { q: "What is the capital of New Zealand?", a: ["Auckland", "Wellington", "Christchurch", "Hamilton"], c: 1 },
      { q: "The Andes mountain range runs along which continent?", a: ["Africa", "Asia", "South America", "Europe"], c: 2 },
      { q: "Which country has the most natural lakes in the world?", a: ["Russia", "Canada", "USA", "Finland"], c: 1 },
    ],
    History: [
      { q: "In which year did World War II end?", a: ["1918", "1939", "1945", "1950"], c: 2 },
      { q: "The French Revolution began in which year?", a: ["1776", "1789", "1804", "1815"], c: 1 },
      { q: "Which explorer reached the Americas in 1492?", a: ["Magellan", "Columbus", "Vasco da Gama", "Cook"], c: 1 },
      { q: "The Berlin Wall fell in which year?", a: ["1979", "1989", "1991", "1995"], c: 1 },
      { q: "Who was the first Emperor of Rome?", a: ["Julius Caesar", "Augustus", "Nero", "Constantine"], c: 1 },
    ],
  },
  8: {
    Math: [
      { q: "If 2x² = 50 and x is positive, what is x?", a: ["5", "10", "25", "2.5"], c: 0 },
      { q: "A right triangle has legs 3 and 4. What is the hypotenuse?", a: ["5", "7", "6", "12"], c: 0 },
      { q: "What is the slope of the line y = 3x − 2?", a: ["−2", "3", "2", "1/3"], c: 1 },
      { q: "What is √144 + √25?", a: ["17", "13", "169", "7"], c: 0 },
      { q: "Simplify: 2³ × 2⁴.", a: ["128", "64", "512", "256"], c: 0 },
    ],
    Science: [
      { q: "What is the SI unit of force?", a: ["Joule", "Newton", "Watt", "Pascal"], c: 1 },
      { q: "What is the chemical formula for table salt?", a: ["NaCl", "KCl", "NaOH", "HCl"], c: 0 },
      { q: "Approximately how fast does light travel in a vacuum?", a: ["3,000 km/s", "30,000 km/s", "300,000 km/s", "3,000,000 km/s"], c: 2 },
      { q: "What is the most abundant element in the universe?", a: ["Oxygen", "Carbon", "Hydrogen", "Helium"], c: 2 },
      { q: "What type of bond involves the sharing of electrons?", a: ["Ionic", "Covalent", "Metallic", "Hydrogen"], c: 1 },
    ],
    English: [
      { q: "What does 'ubiquitous' mean?", a: ["Rare", "Present everywhere", "Ancient", "Hidden"], c: 1 },
      { q: "A word or phrase that reads the same backward (e.g., 'level') is a?", a: ["Anagram", "Palindrome", "Homonym", "Acronym"], c: 1 },
      { q: "Which word means 'brief and to the point'?", a: ["Verbose", "Concise", "Vague", "Elaborate"], c: 1 },
      { q: "What does the prefix 'omni-' mean?", a: ["Against", "All", "Before", "Around"], c: 1 },
      { q: "The subjunctive mood is used mainly to express?", a: ["Facts", "Commands", "Hypotheticals or wishes", "Questions"], c: 2 },
    ],
    Geography: [
      { q: "What is the capital of Kazakhstan?", a: ["Almaty", "Astana", "Bishkek", "Tashkent"], c: 1 },
      { q: "What is the world's largest country by area?", a: ["Canada", "China", "Russia", "USA"], c: 2 },
      { q: "What is the capital of Morocco?", a: ["Casablanca", "Rabat", "Marrakesh", "Fez"], c: 1 },
      { q: "Lake Baikal, the world's deepest lake, is in which country?", a: ["Mongolia", "Russia", "China", "Kazakhstan"], c: 1 },
      { q: "The Atacama, the driest desert on Earth, is mostly in which country?", a: ["Peru", "Chile", "Argentina", "Bolivia"], c: 1 },
    ],
    History: [
      { q: "In which year was the U.S. Declaration of Independence signed?", a: ["1774", "1776", "1781", "1789"], c: 1 },
      { q: "Who co-wrote 'The Communist Manifesto'?", a: ["Lenin", "Karl Marx", "Stalin", "Adam Smith"], c: 1 },
      { q: "The Magna Carta was signed in which year?", a: ["1066", "1215", "1348", "1492"], c: 1 },
      { q: "Which empire was founded by Genghis Khan?", a: ["Ottoman", "Mongol", "Persian", "Byzantine"], c: 1 },
      { q: "The Renaissance is most associated with which Italian city?", a: ["Rome", "Venice", "Florence", "Milan"], c: 2 },
    ],
  },
};
